services:
  - type: web_service
    name: phishing-vishing-detection
    env: node
    plan: free
    branch: main
    rootDir: ./
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
